# Veri Bilimi için Python: NumPy

## 1. NumPy Nedir?
NumPy, dizilerle çalışmak için kullanılan bir Python kütüphanesidir. Ayrıca doğrusal cebir, fourier dönüşümü ve matrisler alanında çalışmak için de gerekli işlevlere sahiptir. NumPy, 2005 yılında Travis Oliphant tarafından oluşturulmuştur. Açık kaynak kodlu bir projedir ve özgürce kullanabilirsiniz. NumPy, Numeriacal Python (Sayısal Python)’un kısaltmasıdır.

## 2. Neden NumPy Kullanılır?
Python’da dizilerin amacına hizmet eden listelerimiz var, ancak işlenmesi yavaştır. NumPy, geleneksel Python listelerinden 50 kata kadar daha hızlı bir dizi nesnesi sağlamayı amaçlamaktadır. NumPy’deki dizi nesnesi (array) ndarray olarak adlandırılır ve ndarray, çalışmayı çok kolaylaştıran birçok destekleyici işlev sağlar. Diziler, hız ve kaynakların çok önemli olduğu veri biliminde çok sık kullanılır.

## 3. NumPy Neden Listelerden Daha Hızlı?
NumPy bir Python kütüphanesidir ve kısmen Python’da yazılmıştır, ancak hızlı hesaplama gerektiren parçaların çoğu C veya C ++ ile yazılmıştır.

In [1]:
#Numpy kütüphanesini yükleyelim
import numpy as np

In [2]:
#Versiyonunu kontrol edelim
print(np.__version__)

1.21.5


## 4. NumPy Dizisi Oluşturma

In [4]:
a = np.array([1, 2, 3])

type(a)

numpy.ndarray

In [6]:
b = np.array([4, 5, 6])

type(b)

numpy.ndarray

In [57]:
#arange ile bir array oluşturma
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [59]:
np.arange(50, 60)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [112]:
np.arange(1, 30, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [15]:
#zeros ile bir array oluşturma
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
#ones ile bir array oluşturma
np.ones(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
#linspace ile bir array oluşturma
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [63]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

## 5. Çok Boyutlu NumPy Dizisi Oluşturma

In [66]:
a = np.array([[2, 3, 4],
              [3, 4, 5]])

a

array([[2, 3, 4],
       [3, 4, 5]])

In [67]:
b = np.ones((3, 3))

b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
c = np.zeros((3, 3))

c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
#boyut sayısını kontrol etmek
a.ndim

2

In [70]:
#dizinin satır-sütun sayısını bulmak
a.shape

(2, 3)

In [71]:
#dizinin boyut sayısını değiştirmek
d = np.ones((2, 5))

d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
d.reshape(5, 2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
e = np.zeros(shape = (3, 6))

e

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [79]:
e.shape

(3, 6)

In [80]:
e = e.reshape(9, 2)

e

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
e.shape

(9, 2)

## 6. Diziden Eleman Seçmek

- Bir diziden eleman seçimi yapmak için **köşeli parantez** kullanılır.
- Köşeli parantez içine tek bir indeks ya da bir aralık girilebilir.
- İlk girilen değer **satır indeksi**, ikinci girilen değer sütun indeksidir.

In [83]:
#Tek boyutlu diziden eleman seçmek
a = np.array([8, 9, 10, 11, 12, 13, 14, 15])

a

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [84]:
#Oluşturulan tek boyutlu dizinin ilk elemanını yazdırınız 
a[0]

8

In [85]:
#Oluşturulan tek boyutlu dizinin ikinci elemanını yazdırınız 
a[1]

9

In [86]:
#Oluşturulan tek boyutlu dizinin son elemanını yazdırınız 
a[-1]

15

In [87]:
#Oluşturulan tek boyutlu dizinin sondan ikinci elemanını yazdırınız 
a[-2]

14

In [88]:
#Çok boyutlu diziden eleman seçmek
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
#Oluşturulan çok boyutlu dizinin ilk elemanını yazdırınız 
a[0]

array([1, 2, 3])

In [91]:
#Oluşturulan çok boyutlu dizinin son elemanını yazdırınız 
a[-1]

array([7, 8, 9])

In [93]:
#Oluşturulan çok boyutlu dizinin 1. satır ve 2. sütun değerini yazdırınız
a[1, 2]

6

In [96]:
#Oluşturulan çok boyutlu dizinin 2. satır ve 1. sütun değerini yazdırınız
a[2, 1]

8

In [97]:
#Oluşturulan çok boyutlu dizinin tüm satırlarını ve 1. sütunu yazdırınız
a[:, 1]

array([2, 5, 8])

In [98]:
#Oluşturulan çok boyutlu dizinin tüm sütunlarını ve ilk satırını yazdırınız
a[0, :]

array([1, 2, 3])

## 7. NumPy ile Matematiksel İşlemler

In [110]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

b = np.zeros(10)

c = np.ones(10)

In [114]:
#Toplama
a + b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [117]:
#Çıkarma
a - c

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [118]:
#Çarpma
a * b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
#Bölme
a / c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## 8. NumPy ile Özel İşlemler

NumPy toplama, çıkarma gibi basit matematiksel işlemlerin yanında trigonometrik, logaritmik, üstel fonksiyonlar gibi daha kompleks fonksiyonlarla da çalışma imkanı sağlar.

In [121]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a = a.reshape(3,3)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
#Sinus
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [125]:
#Cosinus
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [128]:
#Logarithmic
print(np.log(a))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


# Alıştırma 1

1 ile 9 arasında sayılardan oluşan bir dizi oluşturunuz.

In [135]:
#1.çözüm
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

type(a)

numpy.ndarray

In [136]:
#2.çözüm
a = np.arange(1, 10)

a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Alıştırma 2

Oluşturduğunuz 1'e 9'luk matrisi 3'e 3'lük olarak düzenleyiniz.

In [138]:
a = a.reshape(3, 3)

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Alıştırma 3

Oluşan matrisi ilk satırındaki değerleri getiriniz.

In [140]:
a[0]

array([1, 2, 3])

# Alıştırma 4

Oluşan matrisi ilk iki satırındaki değerleri getiriniz.

In [143]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

# Alıştırma 5

Oluşan matrisi 2. satır 3. sütunundaki değeri getiriniz.

In [145]:
a[1, 2]

6

# Alıştırma 5

Oluşan matrisin satır-sütun sayısını kontrol ediniz, aynı satır ve sütun sayısına sahip 1'lerden oluşan bir matris ile toplayınız.

In [146]:
print(a.shape)

(3, 3)


In [149]:
b = np.ones((3, 3))

b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [150]:
a = a + b

print(a)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


# Kaynakça

- https://medium.com/bili%C5%9Fim-hareketi/veri-bilimi-i%CC%87%C3%A7in-temel-python-k%C3%BCt%C3%BCphaneleri-1-numpy-750429a0d8e5

- https://kerteriz.net/python-numpy-kullanimi-nedir-ve-nasil-kullanilir/